### ISSUE TITLE
Twitterは、meta name

### ISSUE THREAD

**Issue by Mogyuchi** [Mogyuchi/angular-mogyuchi.com#23]

**Comment by hiraginoyuki** [comment]
わら

**Comment by Mogyuchi** [comment]
![AEBBCFC2-EE6B-4ED5-A290-EAA6A403AF2C](https://user-images.githubusercontent.com/69337624/139339577-a8b9b4b5-36ec-4087-bd68-2308f91c3481.jpeg)
`property`で良い模様。
